#
# This source file is part of the Stanford Spezi Template Application project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  reuse_action:
    name: REUSE Compliance Check
    uses: StanfordSpezi/.github/.github/workflows/reuse.yml@reuseCISetup
  swiftlint:
    name: SwiftLint
    uses: StanfordSpezi/.github/.github/workflows/swiftlint.yml@reuseCISetup
  buildandtest:
    name: Build and Test
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@reuseCISetup
    with:
      artifactname: TemplateApplication.xcresult
      runsonlabels: '["macos-13"]'
      xcodeversion: 14.2
      setupfirebaseemulator: true
      codeql: true
      customcommand: "firebase emulators:exec 'fastlane test'"
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: buildandtest
    uses: StanfordSpezi/.github/.github/workflows/create-and-upload-coverage-report.yml@reuseCISetup
    with:
      coveragereports: TemplateApplication.xcresult
