#
# This source file is part of the Stanford Spezi Template Application open-source project
#
# SPDX-FileCopyrightText: 2023 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Documentation Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  docs:
    name: Documentation Deployment
    uses: StanfordBDHG/.github/.github/workflows/docc-github-pages.yml@docs
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      scheme: 'TemplateApplication'
