#
# This source file is part of the Stanford Spezi Template Application open-source project
#
# SPDX-FileCopyrightText: 2023 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Documentation Deployment

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  docs:
    name: Documentation Deployment
    uses: StanfordBDHG/.github/.github/workflows/docc-github-pages.yml@docs
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      scheme: 'TemplateApplication'
      dryrun: ${{ github.ref != 'main' && true || false }}
