#
# This source file is part of the Stanford Spezi open-source project
#
# SPDX-FileCopyrightText: 2023 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Documentation Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploydocs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Check environment
        run: |
          xcodebuild -version
          swift --version
          echo "env.selfhosted: ${{ env.selfhosted }}"
      - name: Build DocC
        run: |
          xcodebuild docbuild -scheme TemplateApplication \
            -derivedDataPath .derivedData \
            -destination 'generic/platform=iOS' \
            -skipPackagePluginValidation \
            CODE_SIGN_IDENTITY=""  \
            CODE_SIGNING_REQUIRED=NO
          $(xcrun --find docc) process-archive \
            transform-for-static-hosting .derivedData/Build/Products/Debug-iphoneos/TemplateApplication.doccarchive \
            --hosting-base-path SpeziTemplateApplication \
            --output-path .docs
          echo "<script>window.location.href += \"/documentation/templateapplication\"</script>" > .docs/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
