#
# This source file is part of the Stanford Biodesign Digital Health Group open-source organization
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Test using xcodebuild or run fastlane

on:
  workflow_call:
    inputs:
      arguments:
        description: 'Arguments passed to the firebase deploy command'
        required: false
        type: string
        default: ''
    secrets:
      GOOGLE_APPLICATION_CREDENTIALS:
        description: 'Content of the private key JSON file for the service account. You can lean more on how to generate the JSON at https://firebase.google.com/docs/app-distribution/authenticate-service-account'
        required: true

jobs:
  deployfirebase:
    name: Deploy Firebase Project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup NodeJS
      uses: actions/setup-node@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '17'
    - name: Install Firebase CLI Tools
      run: npm install -g firebase-tools
    - name: Deploy to Firebase
      run: |
        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > $RUNNER_TEMP/google-application-credentials.json
        export GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/google-application-credentials.json
        firebase deploy ${{ inputs.arguments }}
      env:
        GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    - name: Clean up Google application credentials
      if: always()
      run: |
        rm -rf $RUNNER_TEMP/google-application-credentials.json || true
